<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <SelfContained>false</SelfContained>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>notification_banner</RootNamespace>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <AssemblyName>banner</AssemblyName>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <Version>3.0.0.0</Version>
    <Authors>Bluscream, Belphemur, Cursor AI</Authors>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ActionCenterListener\ActionCenterListener.csproj" />
  </ItemGroup>
</Project>